/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,js,jsx,ts,tsx,vue,svelte}',
    './components/**/*.{html,js,jsx,ts,tsx,vue,svelte}',
    './pages/**/*.{html,js,jsx,ts,tsx,vue,svelte}',
    './app/**/*.{html,js,jsx,ts,tsx,vue,svelte}',
    './**/*.html',
  ],
  safelist: [
    // Core glassmorphism colors
    'from-indigo-900',
    'via-purple-900', 
    'to-pink-900',
    'bg-gradient-to-br',
    'backdrop-blur-sm',
    // Text colors
    'text-white',
    'text-white/60',
    'text-white/70',
    'text-white/80',
    'text-white/40',
    // Background variations
    'bg-white/5',
    'bg-white/10',
    'bg-white/20',
    'bg-white/30',
    'hover:bg-white/20',
    'hover:bg-white/30',
    // Borders
    'border-white/20',
    'border-white/40',
    'border-white/60',
    'hover:border-white/40',
    // Shadows and effects
    'shadow-sm',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    'hover:shadow-2xl',
    'drop-shadow-2xl',
    // Border radius
    'rounded',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-full',
    // Transitions and animations
    'transition-all',
    'transition-colors',
    'duration-200',
    'duration-300',
    'duration-500',
    'ease-out',
    // Hover and interaction states
    'hover:scale-105',
    'hover:scale-110',
    'active:scale-95',
    'hover:text-white',
    'cursor-pointer',
    // Animation effects
    'animate-pulse',
    'scale-100',
    'scale-110',
    'rotate-12',
    'transform',
    // Layout utilities
    'fixed',
    'absolute',
    'relative',
    'inset-0',
    'z-10',
    'z-50',
    'flex',
    'flex-col',
    'grid',
    'grid-cols-2',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'space-y-2',
    'space-y-3',
    'space-y-6',
    'justify-center',
    'justify-between',
    'items-center',
    'text-center',
    // Spacing
    'p-2',
    'p-4',
    'p-6',
    'px-2',
    'px-3',
    'px-4',
    'px-6',
    'py-1',
    'py-2',
    'py-3',
    'mx-auto',
    'mb-1',
    'mb-2',
    'mb-3',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-12',
    'mt-2',
    'mt-3',
    'mt-8',
    // Sizes
    'w-5',
    'w-7',
    'w-8',
    'w-10',
    'w-16',
    'w-20',
    'w-48',
    'w-64',
    'w-full',
    'h-5',
    'h-7',
    'h-8',
    'h-10',
    'h-20',
    'h-40',
    'h-48',
    'h-64',
    'max-w-md',
    'max-h-60',
    'min-h-screen',
    // Typography
    'text-xs',
    'text-sm',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-4xl',
    'text-6xl',
    'text-9xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'font-mono',
    // Focus states
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-white/40',
    // Placeholder
    'placeholder-white/50',
    // Overflow
    'overflow-y-auto',
    // Group interactions
    'group',
    'group-hover:opacity-100',
    'opacity-0',
    // Special utilities
    'underline',
    'disabled:bg-white/10',
    'flex-1',
    'self-center',
  ],
  theme: {
    extend: {
      // Custom animations
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-subtle': 'bounce 1s infinite',
      },
      // Custom backdrop blur
      backdropBlur: {
        xs: '2px',
      },
      // Custom shadows
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'glass-lg': '0 15px 35px rgba(31, 38, 135, 0.2)',
      },
      // Custom border radius for perfect circles
      borderRadius: {
        'xl2': '1.25rem',
      }
    },
  },
  plugins: [],
} 